baseURL = "https://kyungkoo.github.io/"
languageCode = "en-us"
title = "devlog"
theme = "anubis"

[author]
  name = "kyungkoo"

[params]
  author = "kyungkoo"
  readMore = false
  paginationSinglePost = true
  style = "light-without-switcher"

[taxonomies]
  tag = "tags"
  category = "categories"  

#[[menu.main]]
#  identifier = "about"
#  name = "About"
#  url = "/about/"
#  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 1

[pagination]
  pageSize = 10